<script setup lang="ts">
import { useQuery, useMutation, useQueryClient } from "@tanstack/vue-query";
import DataTable from "primevue/datatable";
import Column from "primevue/column";
import Button from "primevue/button";
import Tag from "primevue/tag";
import { api } from "@/api/client";
import { formatAmount } from "@/utils/money";

interface Invoice {
  invoice_id: string;
  customer_id: string;
  invoice_type: string;
  currency: string;
  amount: string;
  balance_due: string;
  status: string;
  issue_date: string;
  due_date: string;
  created_at: string;
}

const queryClient = useQueryClient();

const { data, isLoading } = useQuery<Invoice[]>({
  queryKey: ["awaiting-finalization"],
  queryFn: async () => (await api.get<Invoice[]>("/invoices/awaiting-finalization")).data,
});

const finalize = useMutation({
  mutationFn: (id: string) => api.post(`/invoices/${id}/finalize`),
  onSuccess: () => queryClient.invalidateQueries({ queryKey: ["awaiting-finalization"] }),
});

const voidInvoice = useMutation({
  mutationFn: (id: string) =>
    api.post(`/invoices/${id}/void`, { reason: "voided from finalization queue" }),
  onSuccess: () => queryClient.invalidateQueries({ queryKey: ["awaiting-finalization"] }),
});
</script>

<template>
  <section>
    <header class="page-header">
      <div>
        <h1>Awaiting Finalization</h1>
        <p class="subtitle">
          DRAFT invoices generated by the scheduler or manual actions. Approve to send.
        </p>
      </div>
    </header>

    <DataTable :value="data ?? []" :loading="isLoading" data-key="invoice_id" striped-rows>
      <template #empty>
        <div class="empty-state">
          <i class="pi pi-check-circle" />
          <div>No drafts waiting. The finalization queue is clear.</div>
        </div>
      </template>
      <Column field="invoice_type" header="Type">
        <template #body="{ data: row }">
          <Tag :value="row.invoice_type" severity="info" />
        </template>
      </Column>
      <Column field="currency" header="Currency" />
      <Column header="Amount" :body-style="{ textAlign: 'right' }" :header-style="{ textAlign: 'right' }">
        <template #body="{ data: row }">
          <span class="num">{{ formatAmount(row.amount, row.currency) }}</span>
        </template>
      </Column>
      <Column field="issue_date" header="Issued" />
      <Column field="due_date" header="Due" />
      <Column header="Actions">
        <template #body="{ data: row }">
          <div class="actions">
            <Button
              label="Finalize"
              icon="pi pi-check"
              size="small"
              :loading="finalize.isPending.value"
              @click="finalize.mutate(row.invoice_id)"
            />
            <Button
              label="Void"
              icon="pi pi-times"
              size="small"
              severity="secondary"
              text
              :loading="voidInvoice.isPending.value"
              @click="voidInvoice.mutate(row.invoice_id)"
            />
          </div>
        </template>
      </Column>
    </DataTable>
  </section>
</template>

<style scoped>
.actions { display: flex; gap: 0.4rem; }
.num { font-variant-numeric: tabular-nums; }
</style>
